[package]
name = "actix_web_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" # Or a more recent version

